"""Load and merge YAML config files into a ProjectConfig."""

from __future__ import annotations

from pathlib import Path

import yaml
from rich.console import Console

from src.models import (
    AssigneesConfig,
    HierarchyConfig,
    LabelsConfig,
    MilestoneConfig,
    ProjectBoard,
    ProjectConfig,
    ProjectInfo,
    TypesConfig,
)

console = Console()


def _load_yaml(path: Path) -> dict:
    """Load a YAML file and return its contents as a dict."""
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data or {}


def load_repo_config(config_dir: Path) -> ProjectInfo:
    """Load repo.yaml → ProjectInfo."""
    data = _load_yaml(config_dir / "repo.yaml")
    projects = []
    for p in data.get("projects", []):
        projects.append(ProjectBoard(**p))
    return ProjectInfo(
        repo=data["repo"],
        owner=data["owner"],
        projects=projects,
    )


def load_milestones_config(config_dir: Path) -> MilestoneConfig:
    """Load milestones.yaml → MilestoneConfig."""
    data = _load_yaml(config_dir / "milestones.yaml")
    return MilestoneConfig(milestones=data.get("milestones", []))


def load_labels_config(config_dir: Path) -> LabelsConfig:
    """Load labels.yaml → LabelsConfig."""
    data = _load_yaml(config_dir / "labels.yaml")
    return LabelsConfig(labels=data.get("labels", []))


def load_assignees_config(config_dir: Path) -> AssigneesConfig:
    """Load assignees.yaml → AssigneesConfig."""
    data = _load_yaml(config_dir / "assignees.yaml")
    return AssigneesConfig(assignees=data.get("assignees", []))


def load_types_config(config_dir: Path) -> TypesConfig:
    """Load types.yaml → TypesConfig.

    types.yaml is auto-generated by gather-config and contains the list of
    GitHub native issue types available in the repo.
    """
    path = config_dir / "types.yaml"
    if not path.exists():
        return TypesConfig()
    data = _load_yaml(path)
    return TypesConfig(types=data.get("types", []))


def load_hierarchy_config(config_dir: Path) -> HierarchyConfig:
    """Load hierarchy.yaml → HierarchyConfig.

    hierarchy.yaml is user-editable and contains level definitions with
    type configuration (title prefix, default labels, body template,
    github type mapping) and parent-child rules.
    """
    path = config_dir / "hierarchy.yaml"
    if not path.exists():
        return HierarchyConfig()
    data = _load_yaml(path)
    hierarchy_data = data.get("hierarchy", {})
    linking_data = data.get("linking", {})
    return HierarchyConfig(
        levels=hierarchy_data.get("levels", []),
        linking=linking_data,
    )


def load_project_config(config_dir: Path) -> ProjectConfig:
    """Load all config files and merge into a single ProjectConfig.

    Cross-validates:
    - hierarchy level default_labels must exist in labels.yaml
    - hierarchy level github_type must exist in types.yaml (if set)

    If validation fails, the hierarchy is flagged as invalid with specific
    error messages rather than silently proceeding.
    """
    config_dir = Path(config_dir)

    repo_info = load_repo_config(config_dir)
    milestones = load_milestones_config(config_dir)
    labels = load_labels_config(config_dir)
    assignees = load_assignees_config(config_dir)
    types = load_types_config(config_dir)
    hierarchy = load_hierarchy_config(config_dir)

    config = ProjectConfig(
        repo_info=repo_info,
        milestones=milestones,
        labels=labels,
        assignees=assignees,
        types=types,
        hierarchy=hierarchy,
    )

    # Cross-validate hierarchy against labels and types
    validation_errors = validate_hierarchy(config)
    if validation_errors:
        error_msg = "hierarchy.yaml is invalid:\n" + "\n".join(
            f"  - {err}" for err in validation_errors
        )
        raise ValueError(error_msg)

    return config


def validate_hierarchy(config: ProjectConfig) -> list[str]:
    """Validate hierarchy.yaml references against labels.yaml and types.yaml.

    Returns a list of validation error messages. Empty list = valid.
    """
    errors: list[str] = []
    valid_labels = config.get_valid_label_names()
    valid_github_types = config.get_valid_github_types()
    level_names = set(config.hierarchy.get_level_names())

    for level in config.hierarchy.levels:
        # Validate default_labels exist in labels.yaml
        for label in level.default_labels:
            if label not in valid_labels:
                errors.append(
                    f"Level '{level.name}' references default label '{label}' "
                    f"which does not exist in labels.yaml. "
                    f"Available labels: {', '.join(sorted(valid_labels)) or '(none)'}"
                )

        # Validate github_type exists in types.yaml (if set)
        if level.github_type and valid_github_types:
            if level.github_type not in valid_github_types:
                errors.append(
                    f"Level '{level.name}' references github_type '{level.github_type}' "
                    f"which does not exist in types.yaml. "
                    f"Available types: {', '.join(sorted(valid_github_types))}"
                )

        # Validate can_have_children references valid level names
        for child_name in level.can_have_children:
            if child_name not in level_names:
                errors.append(
                    f"Level '{level.name}' lists '{child_name}' in can_have_children "
                    f"but no level with that name exists. "
                    f"Available levels: {', '.join(sorted(level_names))}"
                )

    return errors
